name: admin_processes
description: "Sistema de procesos administrativos organizados para facilitar el logro eficiente de objetivos, con acceso ágil y revisión continua desde cualquier dispositivo."
publish_to: 'none'
version: 0.1.0+2

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-VariableFont_wght.ttf

    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
