name: admin_processes
description: "Visualize and organize administrative processes with touch navigation and interactive lists."
publish_to: 'none'
version: 0.2.0+5

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.0
  path: ^1.8.3
  file_picker: ^8.1.2
  path_provider: ^2.1.4
  share_plus: ^12.0.0
  flutter_linkify: ^6.0.0
  url_launcher: ^6.3.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  msix: ^3.16.12
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/logo_400.png

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-VariableFont_wght.ttf

    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf

flutter_launcher_icons:
  windows:
    generate: true
    image_path: "assets/logo_400.png"
    icon_size: 48


msix_config:
  display_name: admin_processes
  publisher_display_name: Javert Galicia
  identity_name: JavertGalicia.adminprocesses
  publisher: CN=2E6F20B6-F5D2-4834-8474-C87CD7C313F1
  sign_msix: false
  msix_version: 2.0.1.0
  logo_path: "assets/logo_400.png"
